# Meta specification of the page
site_name: PyMMDT Docs

# Plugins
plugins:
  - search
  - awesome-pages

# Construct the navigation between the pages
nav: 
  - Home: index.md
  - About: about.md
  - ... # api-docs

# Select theme
theme: readthedocs
