# Meta specification of the page
site_name: PyMMDT Docs

# Plugins
plugins:
  - search
  - awesome-pages

# Select theme
theme: readthedocs

# nav
order: desc
nav:
  - index.md
  - installation.md
  - basics.md
  - tutorials.md
  - about.md
  - API Reference:
    - Core:
      - api-docs/data_stream.md
      - api-docs/data_sample.md
      - api-docs/process.md
      - api-docs/collector.md
      - api-docs/session.md
      - api-docs/analyzer.md
    - Tabular:
      - api-docs/tabular.md
      - api-docs/tabular.tabular_data_stream.md
    - Video:
      - api-docs/video.md
      - api-docs/video.processes.md
      - api-docs/video.video_data_stream.md
