on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python
        uses: actions/setup-python@v2

      - uses: actions/checkout@v2

      - name: Install dependencies locally
        run: |
          sudo apt-get update

      - name: Install ChimeraPy
        run: |
          python3 -m pip install '.[test]'

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
