name: deploy

on:
  release:
    types: [published]

jobs:

  # Build the package - including documentation
  deploy:

    # Run on latest ubuntu
    name: PyPI Upload
    runs-on: ubuntu-20.04 # ubuntu-latest
    
    # The process
    steps:
      - uses: actions/checkout@v2

        # Setting up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade --disable-pip-version-check pip
          python -m pip install --upgrade build twine

      - name: Build Package
        run: |
          python -m build

      - name: Upload to PyPI via Twine
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload --verbose -u '__token__' dist/*
