name: Documentation

on:
  push:
    branches:
    - main

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:

    - name: Setup Python
      uses: actions/setup-python@master

    - name: Checkout to another branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        path: ChimeraPy

    - name: Install ChimeraPy
      run: |
        pip install -e .

    - name: Installing Dependencies
      run: |
        cd docs/
        pip install -r requirements.txt
        cd ..

    - name: Build documentation
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        cd docs/
        make html
        mv docs/_build/html gh-pages

    - name: Deploy documentation
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: gh-pages
