name: docs
on:
  push:
    branches: 
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      # Installing the needed dependencies to deploy Docs Page
      - run: pip install \
             mkdocs-material \
             mkdocs-awesome-pages-plugin
      # Generating the api-docs
      - run: lazydocs \
             --output-path="./docs/api-docs" 
             mm
      # Deploying GitHub Pages
      - run: mkdocs gh-deploy --force
