name: Test

# Look at this: https://github.com/iterative/dvc/pull/7213
# Forum: https://discuss.dvc.org/t/cml-github-actions-google-drive-service-account/795/3?fbclid=IwAR21DBJ3bP2m3VwZ7EUp4U1ik0YQbNRgAIdemg14msCC7UtnaBao81oTTDE
# https://github.com/iterative/cml#using-cml-with-dvc
# https://github.com/iterative/dvc.org/blob/master/content/docs/user-guide/setup-google-drive-remote.md
# https://www.ravirajag.dev/blog/mlops-github-actions

on:
  push:

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    # The process
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - uses: actions/checkout@v2

      - name: Install dependencies locally
        run: |
          sudo apt-get update

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg libsm6 libxext6 -y
          python3 -m pip install --upgrade pip
          python3 -m pip install '.[test]'
          docker build -t chimerapy .

      - name: Install MacOS dependencies
        if: matrix.os == 'macos-latest'
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install '.[test]'

      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install .[test]

      - name: Perform tests
        run: |
          coverage run --source=chimerapy -m pytest test/

      - name: Upload coverage data to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
          COVERALLS_PARALLEL: true


  coveralls:
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
