# name: Testing the package in various scenarios
#   # https://github.com/psf/black/actions/runs/17158461/workflow
# on:
#   push:
#     paths-ignore:
#       - "docs/**"
#       - "*.md"

#   pull_request:
#     paths-ignore:
#       - "docs/**"
#       - "*.md"

# jobs:

#   # Goal is to test the package with various version of python
#   test:

#     # We want to run on external PRs, but not on our own internal PRs as they'll be run
#     # by the push to the branch. Without this if check, checks are duplicated since
#     # internal PRs match both the push and pull_request events.
#     if:
#       github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
#       github.repository

#     # Run on latest ubuntu for various version of python
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: false
#       matrix:
#         python-version: [3.6, 3.7, 3.8, 3.9]
#         os: [ubuntu-latest, macOS-latest, windows-latest]

#     # The process
#     steps:
#       # Create environment
#       - uses: actions/checkout@v2

#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v2
#         with:
#           python-version: ${{ matrix.python-version }}

#       # Install pymmdt locally
#       - name: Install dependencies locally
#         run: |
#           if [ "$RUNNER_OS" == "Linux" ]; then
#             sudo apt-get update
#             # sudo apt-get install -y python3-opencv
#             sudo apt-get install ffmpeg libsm6 libxext6 -y
#           fi
#           # All need to run the following
#           python3 -m pip install --upgrade pip
#           python3 -m pip install .

#       # Test the build
#       - name: Test with unittest
#         run: |
#           python -m unittest discover
