name: Test

# Look at this: https://github.com/iterative/dvc/pull/7213
# Forum: https://discuss.dvc.org/t/cml-github-actions-google-drive-service-account/795/3?fbclid=IwAR21DBJ3bP2m3VwZ7EUp4U1ik0YQbNRgAIdemg14msCC7UtnaBao81oTTDE
# https://github.com/iterative/cml#using-cml-with-dvc
# https://github.com/iterative/dvc.org/blob/master/content/docs/user-guide/setup-google-drive-remote.md
# https://www.ravirajag.dev/blog/mlops-github-actions

on:
  push:

jobs:
  test:

    runs-on: ubuntu-latest

    # The process
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2

      - uses: actions/checkout@v2

      - name: Install dependencies locally
        run: |
          sudo apt-get update

      - name: Install dependencies and ChimeraPy
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            # sudo apt-get install -y python3-opencv
            sudo apt-get install ffmpeg libsm6 libxext6 -y
          fi
          # All need to run the following
          python3 -m pip install --upgrade pip
          python3 -m pip install '.[test]'

      - name: PyTest
        run: |
          pytest
